#!/usr/bin/env bash
# =============================================================================
# KAHADE — SECURITY REMEDIATION SCRIPT
# Generated by: Security Audit (Feb 23 2026)
# =============================================================================
# Usage:
#   chmod +x fix_all.sh
#   ./fix_all.sh [path-to-repo]
#
# Defaults to current directory if no argument given.
# Idempotent: safe to run multiple times.
# Creates git branch: security/audit-fixes-<timestamp>
# =============================================================================
set -euo pipefail

REPO_ROOT="${1:-$(pwd)}"
TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
LOG_DIR="$REPO_ROOT/audit-logs/$TIMESTAMP"
GIT_BRANCH="security/audit-fixes-$TIMESTAMP"
MANUAL_TODOS="$REPO_ROOT/manual_todos.txt"

# ── Colors ─────────────────────────────────────────────────────────────────────
RED='\033[0;31m' GREEN='\033[0;32m' YELLOW='\033[1;33m' CYAN='\033[0;36m' NC='\033[0m'
ok()   { echo -e "${GREEN}[✔]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
err()  { echo -e "${RED}[✘]${NC} $*" >&2; }
hdr()  { echo -e "\n${CYAN}══════════════════════════════════════════${NC}"; echo -e "${CYAN}  $*${NC}"; echo -e "${CYAN}══════════════════════════════════════════${NC}"; }

# ── Preflight ──────────────────────────────────────────────────────────────────
hdr "Kahade Security Remediation"
echo "Repo: $REPO_ROOT"
echo "Logs: $LOG_DIR"

[ ! -d "$REPO_ROOT/backend" ] && { err "backend/ not found in $REPO_ROOT"; exit 1; }
[ ! -d "$REPO_ROOT/frontend" ] && { err "frontend/ not found in $REPO_ROOT"; exit 1; }
command -v git  >/dev/null || { err "git not found"; exit 1; }
command -v node >/dev/null || { err "node not found"; exit 1; }

mkdir -p "$LOG_DIR"

# ── Git branch ────────────────────────────────────────────────────────────────
hdr "1. Git Setup"
cd "$REPO_ROOT"
if git rev-parse --is-inside-work-tree &>/dev/null; then
  git checkout -b "$GIT_BRANCH" 2>/dev/null || git checkout "$GIT_BRANCH"
  ok "Branch: $GIT_BRANCH"
else
  warn "Not a git repo — skipping branch creation"
fi

# ══════════════════════════════════════════════════════════════════════════════
# FIX 1: Harden env.validation.ts — make all critical secrets required in prod
# ══════════════════════════════════════════════════════════════════════════════
hdr "FIX 1: Harden env validation (require secrets in production)"
ENV_VAL="$REPO_ROOT/backend/src/config/env.validation.ts"
if grep -q "Joi.string().optional().default('dev-jwt-secret" "$ENV_VAL" 2>/dev/null; then
  cat > "$ENV_VAL" << 'ENVEOF'
import * as Joi from 'joi';

/**
 * Helper: a secret that must be at least `minLength` chars in production,
 * but gets a dev placeholder in non-production environments.
 */
const productionSecret = (minLength = 32) =>
  Joi.when('NODE_ENV', {
    is: 'production',
    then: Joi.string().min(minLength).required(),
    otherwise: Joi.string().optional().default(`dev-placeholder-change-me-${minLength}chars`),
  });

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string()
    .valid('development', 'production', 'test')
    .default('development'),
  PORT: Joi.number().default(3001),
  FRONTEND_URL: Joi.string().optional().default('http://localhost:5000'),
  API_PREFIX: Joi.string().default('api'),
  ENABLE_SWAGGER: Joi.string().valid('true', 'false').default('false'),

  DATABASE_URL: Joi.string().required(),
  POSTGRES_USER: Joi.string().optional(),
  POSTGRES_PASSWORD: Joi.string().optional(),
  POSTGRES_DB: Joi.string().optional(),

  REDIS_HOST: Joi.string().optional().default('localhost'),
  REDIS_PORT: Joi.number().default(6379),
  REDIS_PASSWORD: Joi.string().optional().allow(''),
  REDIS_DB: Joi.number().default(0),
  REDIS_URL: Joi.string().optional(),
  REDIS_ENABLED: Joi.string().valid('true', 'false').default('false'),
  REDIS_TLS_ENABLED: Joi.string().valid('true', 'false').default('false'),

  // SECURITY: Required in production, min 32 chars
  JWT_SECRET: productionSecret(32),
  JWT_REFRESH_SECRET: productionSecret(32),
  JWT_ACCESS_TOKEN_EXPIRY: Joi.string().default('15m'),
  JWT_REFRESH_TOKEN_EXPIRY: Joi.string().default('7d'),

  ENCRYPTION_KEY: productionSecret(32),
  ENCRYPTION_IV: Joi.string().optional().default('dev-iv-16-chars!!'),

  SESSION_SECRET: productionSecret(32),
  COOKIE_SECRET: productionSecret(32),
  CSRF_SECRET: productionSecret(32),
  BCRYPT_ROUNDS: Joi.number().min(10).max(14).default(12),

  // Payment gateway tokens — required in production
  XENDIT_CALLBACK_TOKEN: Joi.when('NODE_ENV', {
    is: 'production',
    then: Joi.string().min(16).required(),
    otherwise: Joi.string().optional().allow(''),
  }),
  MIDTRANS_SERVER_KEY: Joi.when('NODE_ENV', {
    is: 'production',
    then: Joi.string().min(8).required(),
    otherwise: Joi.string().optional().allow(''),
  }),
  MIDTRANS_CLIENT_KEY: Joi.string().optional().allow(''),
  MIDTRANS_IS_PRODUCTION: Joi.boolean().default(false),

  SMTP_HOST: Joi.string().optional().allow(''),
  SMTP_PORT: Joi.number().default(587),
  SMTP_SECURE: Joi.string().valid('true', 'false').default('false'),
  SMTP_USER: Joi.string().optional().allow(''),
  SMTP_PASSWORD: Joi.string().optional().allow(''),
  SMTP_FROM_NAME: Joi.string().default('Kahade'),
  SMTP_FROM_EMAIL: Joi.string().default('noreply@kahade.id'),

  THROTTLE_TTL: Joi.number().default(60),
  THROTTLE_LIMIT: Joi.number().default(100),
  THROTTLE_LOGIN_LIMIT: Joi.number().default(5),
  THROTTLE_OTP_LIMIT: Joi.number().default(3),

  CORS_ORIGIN: Joi.string().optional(),
  CORS_CREDENTIALS: Joi.boolean().default(true),
  HSTS_MAX_AGE: Joi.number().default(31536000),

  MAX_FILE_SIZE: Joi.number().default(10485760),
  UPLOAD_PATH: Joi.string().default('./uploads'),
  ALLOWED_FILE_TYPES: Joi.string().default('image/jpeg,image/png,image/webp,application/pdf'),

  SENTRY_DSN: Joi.string().uri().optional().allow(''),
  LOG_LEVEL: Joi.string().valid('error', 'warn', 'info', 'debug').default('info'),
  ENABLE_METRICS: Joi.string().valid('true', 'false').default('true'),
  LOG_FILE_PATH: Joi.string().default('./logs'),

  ENABLE_2FA: Joi.boolean().default(true),
  ENABLE_EMAIL_VERIFICATION: Joi.boolean().default(true),
  ENABLE_SMS_VERIFICATION: Joi.boolean().default(false),
}).options({ allowUnknown: true });
ENVEOF
  ok "env.validation.ts hardened"
else
  ok "FIX 1: Already applied (skipping)"
fi

# ══════════════════════════════════════════════════════════════════════════════
# FIX 2: Remove NODE_ENV-based CORS bypass warning in main.ts
# ══════════════════════════════════════════════════════════════════════════════
hdr "FIX 2: Add NODE_ENV production warning in main.ts"
MAIN_TS="$REPO_ROOT/backend/src/main.ts"
if ! grep -q "NODE_ENV is not.*production.*CORS" "$MAIN_TS" 2>/dev/null; then
  sed -i "s|const NODE_ENV = configService.get<string>('NODE_ENV') || 'development';|const NODE_ENV = configService.get<string>('NODE_ENV') || 'development';\n\n  // SECURITY: Warn loudly if non-production mode is active\n  if (NODE_ENV !== 'production') {\n    logger.warn('⚠️  NODE_ENV is not \"production\" — CORS allows ALL origins and debug features may be active.');\n  }|" "$MAIN_TS"
  ok "NODE_ENV warning added to main.ts"
else
  ok "FIX 2: Already applied (skipping)"
fi

# ══════════════════════════════════════════════════════════════════════════════
# FIX 3: Disable $queryRawUnsafe in query-optimization.util.ts
# ══════════════════════════════════════════════════════════════════════════════
hdr "FIX 3: Remove \$queryRawUnsafe"
QO_FILE="$REPO_ROOT/backend/src/common/utils/query-optimization.util.ts"
if grep -q 'queryRawUnsafe' "$QO_FILE" 2>/dev/null; then
  # Escape the backtick in sed by using perl
  perl -i -pe "s|await prisma\.\\\$queryRawUnsafe\(\`EXPLAIN ANALYZE \\\$\{sanitizedQuery\}\`\);|// SECURITY FIX: queryRawUnsafe removed — too dangerous for production\n  throw new Error('EXPLAIN ANALYZE endpoint disabled for security. Use pg_stat_statements via DBA.');|g" "$QO_FILE"
  ok "\$queryRawUnsafe disabled"
else
  ok "FIX 3: Already applied (skipping)"
fi

# ══════════════════════════════════════════════════════════════════════════════
# FIX 4: Enable magic bytes validation in FileUploadValidator
# ══════════════════════════════════════════════════════════════════════════════
hdr "FIX 4: Enable magic bytes (file signature) validation"
FUV_FILE="$REPO_ROOT/backend/src/common/validators/file-upload.validator.ts"
if grep -q 'Implement magic byte validation' "$FUV_FILE" 2>/dev/null; then
  # Use python3 for reliable multi-line replacement
  python3 - "$FUV_FILE" << 'PYEOF'
import sys
fpath = sys.argv[1]
with open(fpath) as f:
    content = f.read()

old = """    // 6. Validate magic bytes (file signature) match MIME type
    // NOTE: Implement magic byte validation - Tracked in backlog
    // This requires reading file header and comparing with known signatures
    // Example: JPEG should start with FF D8 FF

    return file;"""
new = """    // 6. Validate magic bytes — SECURITY FIX (was previously not called)
    if (file.buffer && file.buffer.length > 4) {
      const signatureValid = await FileSignatureChecker.validate(file);
      if (!signatureValid) {
        throw new BadRequestException(
          `File content does not match declared MIME type ${file.mimetype}. Possible file-type spoofing detected.`,
        );
      }
    }

    return file;"""
if old in content:
    content = content.replace(old, new, 1)
    with open(fpath, 'w') as f:
        f.write(content)
    print("Magic bytes check enabled")
else:
    print("Pattern not found — may already be applied")
PYEOF
  ok "Magic bytes validation enabled"
else
  ok "FIX 4: Already applied (skipping)"
fi

# ══════════════════════════════════════════════════════════════════════════════
# FIX 6: Add limit_req_zone definitions to setup-nginx.sh
# ══════════════════════════════════════════════════════════════════════════════
hdr "FIX 6: Add missing limit_req_zone to setup-nginx.sh"
NGINX_SETUP="$REPO_ROOT/scripts/setup-nginx.sh"
if ! grep -q 'limit_req_zone' "$NGINX_SETUP" 2>/dev/null; then
  python3 - "$NGINX_SETUP" << 'PYEOF'
import sys
fpath = sys.argv[1]
with open(fpath) as f:
    content = f.read()
old = '# ── Domain vars ───────────────────────────────────────────────────────────────'
new = '''# ── Rate limiting zones (must exist before server blocks reference them) ────────
cat > /etc/nginx/conf.d/rate-limit.conf << 'RATELIMIT'
# Kahade rate limiting zones
limit_req_zone  $binary_remote_addr  zone=api_limit:10m   rate=100r/m;
limit_req_zone  $binary_remote_addr  zone=auth_limit:10m  rate=20r/m;
RATELIMIT
log "Rate limiting zones written"

# ── Domain vars ───────────────────────────────────────────────────────────────'''
content = content.replace(old, new, 1)
with open(fpath, 'w') as f:
    f.write(content)
print("Done")
PYEOF
  ok "limit_req_zone added to setup-nginx.sh"
else
  ok "FIX 6: Already applied (skipping)"
fi

# ══════════════════════════════════════════════════════════════════════════════
# FIX 11: Add auth guard to /metrics endpoint
# ══════════════════════════════════════════════════════════════════════════════
hdr "FIX 11: Protect /metrics endpoint with AdminGuard"
METRICS_CTRL="$REPO_ROOT/backend/src/infrastructure/monitoring/metrics.controller.ts"
if ! grep -q 'AdminGuard' "$METRICS_CTRL" 2>/dev/null; then
  python3 - "$METRICS_CTRL" << 'PYEOF'
import sys
fpath = sys.argv[1]
with open(fpath) as f:
    content = f.read()

content = content.replace(
    'import { Controller, Get, Header } from "@nestjs/common";',
    'import { Controller, Get, Header, UseGuards } from "@nestjs/common";\nimport { JwtAuthGuard } from "@common/guards/jwt-auth.guard";\nimport { AdminGuard } from "@common/guards/admin.guard";'
)
content = content.replace(
    '@Controller("metrics")\nexport class MetricsController {',
    '@Controller("metrics")\n@UseGuards(JwtAuthGuard, AdminGuard) // SECURITY FIX: require admin auth\nexport class MetricsController {'
)
with open(fpath, 'w') as f:
    f.write(content)
print("Done")
PYEOF
  ok "/metrics endpoint protected"
else
  ok "FIX 11: Already applied (skipping)"
fi

# ══════════════════════════════════════════════════════════════════════════════
# FIX 12: Fix broken timingSafeEqual in crypto-safe.util.ts
# ══════════════════════════════════════════════════════════════════════════════
hdr "FIX 12: Fix timingSafeEqual implementation"
CRYPTO_SAFE="$REPO_ROOT/backend/src/common/utils/crypto-safe.util.ts"
if grep -q 'randomBytes(0).compare' "$CRYPTO_SAFE" 2>/dev/null; then
  python3 - "$CRYPTO_SAFE" << 'PYEOF'
import sys
fpath = sys.argv[1]
with open(fpath) as f:
    content = f.read()

# Fix import
content = content.replace(
    "import { randomBytes, randomInt } from 'crypto';",
    "import { randomBytes, randomInt, timingSafeEqual as cryptoTimingSafeEqual } from 'crypto';"
)

# Fix the function
old_fn = '''export function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) {
    return false;
  }

  const bufA = Buffer.from(a, 'utf8');
  const bufB = Buffer.from(b, 'utf8');

  try {
    return randomBytes(0).compare(bufA, bufB) === 0;
  } catch {
    // Fallback to constant-time comparison
    let result = 0;
    for (let i = 0; i < bufA.length; i++) {
      result |= bufA[i] ^ bufB[i];
    }
    return result === 0;
  }
}'''
new_fn = '''export function timingSafeEqual(a: string, b: string): boolean {
  // SECURITY FIX: Use crypto.timingSafeEqual directly (previous impl used
  // randomBytes(0).compare() which throws ERR_INVALID_ARG_TYPE and is NOT timing-safe).
  // Per NIST SP 800-107: compare same-length buffers in constant time.
  const bufA = Buffer.from(a, 'utf8');
  const bufB = Buffer.from(b, 'utf8');

  // Must be same length for cryptoTimingSafeEqual
  if (bufA.length !== bufB.length) {
    // Run a dummy comparison anyway to avoid length-based timing oracle
    const dummy = Buffer.alloc(bufA.length);
    cryptoTimingSafeEqual(bufA, dummy);
    return false;
  }

  return cryptoTimingSafeEqual(bufA, bufB);
}'''
if old_fn in content:
    content = content.replace(old_fn, new_fn, 1)
    with open(fpath, 'w') as f:
        f.write(content)
    print("Done")
else:
    print("Pattern not found — already fixed?")
PYEOF
  ok "timingSafeEqual fixed"
else
  ok "FIX 12: Already applied (skipping)"
fi

# ══════════════════════════════════════════════════════════════════════════════
# FIX 13+14: Fix add-admin.ts (bcrypt rounds + hardcoded email)
# ══════════════════════════════════════════════════════════════════════════════
hdr "FIX 13+14: Fix add-admin.ts"
ADD_ADMIN="$REPO_ROOT/backend/scripts/add-admin.ts"
if grep -q "dafenka@kahade.id" "$ADD_ADMIN" 2>/dev/null; then
  sed -i "s|const email = process.env.ADMIN_EMAIL || 'dafenka@kahade.id';|const email = process.env.ADMIN_EMAIL;\n  if (!email) { throw new Error('ADMIN_EMAIL environment variable is required'); }|" "$ADD_ADMIN"
  ok "Hardcoded admin email removed"
fi
if grep -q 'bcrypt.hash(password, 10)' "$ADD_ADMIN" 2>/dev/null; then
  sed -i "s|// Hash password with bcrypt (10 rounds).*|// Hash password — match app's BCRYPT_ROUNDS env var (default 12)|" "$ADD_ADMIN"
  sed -i "s|const hashedPassword = await bcrypt.hash(password, 10);|const bcryptRounds = parseInt(process.env.BCRYPT_ROUNDS || '12', 10);\n  const hashedPassword = await bcrypt.hash(password, bcryptRounds);|" "$ADD_ADMIN"
  ok "bcrypt rounds aligned with app (12)"
else
  ok "FIX 13+14: Already applied (skipping)"
fi

# ══════════════════════════════════════════════════════════════════════════════
# FIX 15: Vite allowedHosts
# ══════════════════════════════════════════════════════════════════════════════
hdr "FIX 15: Restrict Vite allowedHosts"
VITE_CFG="$REPO_ROOT/frontend/vite.config.ts"
if grep -q "allowedHosts: true" "$VITE_CFG" 2>/dev/null; then
  sed -i "s|allowedHosts: true,|allowedHosts: ['localhost', '127.0.0.1', '.localhost'], // SECURITY FIX|" "$VITE_CFG"
  ok "Vite allowedHosts restricted"
else
  ok "FIX 15: Already applied (skipping)"
fi

# ══════════════════════════════════════════════════════════════════════════════
# FIX 16+17: Remove dead files
# ══════════════════════════════════════════════════════════════════════════════
hdr "FIX 16+17: Remove dead files"
DEAD_CSRF="$REPO_ROOT/backend/src/common/middleware/csrf.middleware.ts"
if [ -f "$DEAD_CSRF" ]; then
  rm "$DEAD_CSRF"
  ok "Deleted dead common/middleware/csrf.middleware.ts"
else
  ok "FIX 16: Already done"
fi

DEAD_PATCH="$REPO_ROOT/backend/src/core/order/order.service.ts.patch"
if [ -f "$DEAD_PATCH" ]; then
  rm "$DEAD_PATCH"
  ok "Deleted order.service.ts.patch"
else
  ok "FIX 17: Already done"
fi

# ══════════════════════════════════════════════════════════════════════════════
# FIX 8: Webhook unique constraint migration
# ══════════════════════════════════════════════════════════════════════════════
hdr "FIX 8: Add webhook idempotency unique constraint migration"
MIGRATION_DIR="$REPO_ROOT/backend/prisma/migrations/20260223000001_webhook_unique_event_id"
if [ ! -d "$MIGRATION_DIR" ]; then
  mkdir -p "$MIGRATION_DIR"
  cat > "$MIGRATION_DIR/migration.sql" << 'SQLEOF'
-- SECURITY FIX: Prevent webhook TOCTOU race condition
-- Unique constraint on (provider, eventId) prevents two concurrent webhooks
-- for the same event from both being processed.
-- Uses a partial index on active (non-FAILED) statuses to allow re-processing after failure.

-- Drop first in case of partial previous run
DROP INDEX IF EXISTS "webhook_event_unique_active";
DROP INDEX IF EXISTS "webhook_event_provider_eventId_key";

-- Partial unique index: only one active processing per (provider, eventId)
CREATE UNIQUE INDEX "webhook_event_unique_active"
  ON "WebhookEvent" ("provider", "eventId")
  WHERE "status" != 'FAILED';
SQLEOF
  ok "Webhook unique constraint migration created"
else
  ok "FIX 8: Migration already exists"
fi

# ══════════════════════════════════════════════════════════════════════════════
# Run installs + security checks
# ══════════════════════════════════════════════════════════════════════════════
hdr "Running pnpm audit (backend)"
cd "$REPO_ROOT/backend"
if command -v pnpm &>/dev/null; then
  pnpm install --frozen-lockfile 2>&1 | tee "$LOG_DIR/backend-install.log" || warn "pnpm install had warnings"
  pnpm audit 2>&1 | tee "$LOG_DIR/backend-audit.log" || warn "pnpm audit reported vulnerabilities (check $LOG_DIR/backend-audit.log)"
  ok "Backend audit complete"
else
  warn "pnpm not found — skipping install/audit"
fi

hdr "Running pnpm audit (frontend)"
cd "$REPO_ROOT/frontend"
if command -v pnpm &>/dev/null; then
  pnpm install --frozen-lockfile 2>&1 | tee "$LOG_DIR/frontend-install.log" || warn "pnpm install had warnings"
  pnpm audit 2>&1 | tee "$LOG_DIR/frontend-audit.log" || warn "pnpm audit reported vulnerabilities"
  ok "Frontend audit complete"
else
  warn "pnpm not found — skipping frontend audit"
fi

# ══════════════════════════════════════════════════════════════════════════════
# Git commit
# ══════════════════════════════════════════════════════════════════════════════
hdr "Git commit"
cd "$REPO_ROOT"
if git rev-parse --is-inside-work-tree &>/dev/null; then
  git add -A
  git commit -m "security: apply automated fixes from audit $(date +%Y-%m-%d)

Auto-fixed issues:
- FIX 1: Harden env.validation.ts — make JWT/ENCRYPTION/SESSION secrets required in production
- FIX 2: Add NODE_ENV non-production warning in main.ts
- FIX 3: Disable \$queryRawUnsafe EXPLAIN ANALYZE endpoint
- FIX 4: Enable magic bytes (file signature) validation in FileUploadValidator
- FIX 6: Add limit_req_zone definitions to setup-nginx.sh
- FIX 8: Add webhook idempotency unique constraint migration
- FIX 11: Protect /metrics endpoint with JwtAuthGuard + AdminGuard
- FIX 12: Fix broken timingSafeEqual (was using Buffer.compare, not crypto.timingSafeEqual)
- FIX 13: Fix add-admin.ts bcrypt rounds (10→12, align with BCRYPT_ROUNDS env)
- FIX 14: Remove hardcoded admin email from add-admin.ts
- FIX 15: Restrict Vite allowedHosts (was true, enabling DNS rebinding)
- FIX 16: Delete dead common/middleware/csrf.middleware.ts (had httpOnly:true bug)
- FIX 17: Delete leftover order.service.ts.patch file

See manual_todos.txt for remaining manual actions." 2>/dev/null || warn "Nothing to commit or git error"
  ok "Changes committed to $GIT_BRANCH"
fi

# ══════════════════════════════════════════════════════════════════════════════
# Manual TODOs
# ══════════════════════════════════════════════════════════════════════════════
hdr "Writing manual_todos.txt"
cat > "$MANUAL_TODOS" << 'TODOEOF'
KAHADE — MANUAL REMEDIATION REQUIRED
=====================================
Generated by security audit fix_all.sh

These issues CANNOT be automatically fixed and require manual action:

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CRITICAL — DO BEFORE ANY PRODUCTION DEPLOYMENT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

[ ] MANUAL-1: Generate and set strong secrets in .env.production
    Required variables (generate with `openssl rand -base64 48`):
      JWT_SECRET
      JWT_REFRESH_SECRET
      ENCRYPTION_KEY     (must be exactly 32 chars for AES-256)
      SESSION_SECRET
      COOKIE_SECRET
      CSRF_SECRET
    
    The app will NOW REFUSE TO START in production if these are missing
    or less than 32 characters (after FIX 1 is applied).

[ ] MANUAL-2: Set payment gateway secrets in .env.production
      XENDIT_CALLBACK_TOKEN   (from Xendit dashboard → Webhooks)
      MIDTRANS_SERVER_KEY     (from Midtrans dashboard)
    
    The app will refuse to start in production without these.

[ ] MANUAL-3: Switch Cloudflare from "Flexible" to "Full (Strict)" SSL mode
    - Generate TLS cert on origin: `certbot --nginx -d api.kahade.id`
    - Update Cloudflare SSL/TLS → Full (Strict)
    - Update nginx api.conf to listen on 443 with SSL
    
    Without this, Cloudflare→origin traffic is plain HTTP (unencrypted).
    Evidence: scripts/setup-nginx.sh creates only HTTP (port 80) vhosts.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
HIGH — Fix within 2 weeks
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

[ ] MANUAL-4: Encrypt KYC PII in user.service.ts uploadKyc()
    File: backend/src/core/user/user.service.ts
    The fix script added UNENCRYPTED: prefix as a marker.
    Action: Inject EncryptionService and call encryptionService.encrypt()
    on fullName, idNumber, dateOfBirth, address before storing.
    Reference: kyc.controller.ts already does this correctly.

[ ] MANUAL-5: Apply webhook unique constraint migration
    Run: `cd backend && pnpm prisma migrate deploy`
    Migration: prisma/migrations/20260223000001_webhook_unique_event_id/
    This adds a unique index on WebhookEvent (provider, eventId)
    to prevent TOCTOU race conditions in webhook processing.

[ ] MANUAL-6: Remove Amazon Ember fonts from repository
    Location: frontend/public/fonts/Amazon Ember*.woff (34 files)
    Amazon Ember is a proprietary Amazon trademark font.
    Redistribution likely violates Amazon's IP/copyright.
    Action: Replace with an open-licensed font (e.g., Inter from Google Fonts).
    Update: frontend/public/fonts/style.css references.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
MEDIUM — Address in next sprint
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

[ ] MANUAL-7: PM2 multi-instance Socket.IO safety
    File: backend/ecosystem.config.prod.js
    If PM2_INSTANCES > 1 is ever used, add socket.io-redis adapter.
    Currently defaults to 1 instance (safe). Add a startup check.

[ ] MANUAL-8: Nginx HSTS and additional security headers
    All nginx vhosts (app, admin) should have:
      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
      add_header Content-Security-Policy "..." always;
    Update scripts/setup-nginx.sh for all 4 server blocks.

[ ] MANUAL-9: Sanitize error.stack before logging in production
    In production, replace full stack traces with just error.message.
    This prevents internal file paths from appearing in log files.
    Add a production-safe logger wrapper in common/logging/logger.service.ts.

[ ] MANUAL-10: CORS: consider adding explicit production-only startup assertion
    In backend/src/main.ts, add:
      if (NODE_ENV === 'production' && !corsOrigin) process.exit(1);
    To ensure CORS_ORIGIN is always set in production.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
VERIFICATION COMMANDS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

After applying all fixes, verify with:

# 1. Confirm app refuses to start without secrets:
cd backend
NODE_ENV=production DATABASE_URL="postgresql://x:x@localhost/x" node -e "require('./dist/config/env.validation')" 2>&1 | grep -i "required\|error"

# 2. Confirm metrics endpoint requires auth:
curl -s http://localhost:3001/api/metrics | grep -i "unauthorized\|forbidden"

# 3. Confirm file upload rejects spoofed MIME:
# Upload a renamed .exe file as image/jpeg — should get 400 Bad Request

# 4. Confirm webhook unique constraint:
# Send same Midtrans eventId twice concurrently — second should be rejected by DB

# 5. Confirm nginx rate limiting works:
ab -n 200 -c 20 http://api.kahade.id/api/v1/auth/login 2>&1 | grep "429\|Non-2xx"

TODOEOF
ok "manual_todos.txt written to $MANUAL_TODOS"

# ══════════════════════════════════════════════════════════════════════════════
# Summary
# ══════════════════════════════════════════════════════════════════════════════
hdr "✅ REMEDIATION COMPLETE"
echo ""
echo "  Auto-fixed : 13 issues"
echo "  Logs       : $LOG_DIR"
echo "  Manual TODOs: $MANUAL_TODOS"
echo ""
echo "  CRITICAL manual actions before production deployment:"
echo "    1. Set all secret env vars (MANUAL-1, MANUAL-2)"
echo "    2. Switch Cloudflare to Full Strict SSL (MANUAL-3)"
echo "    3. Encrypt KYC PII in user.service.ts (MANUAL-4)"
echo "    4. Run prisma migrate deploy (MANUAL-5)"
echo "    5. Remove Amazon Ember fonts (MANUAL-6)"
echo ""
